version: '3.7'
services:

  angular_app:
    build: .
    command: 'npm start --configuration=development'
    ports:
      - '4200:4200' 
      - '49153:49153'
    volumes:
      - .:/frontend
    networks:
      - backend_api

networks:
  backend_api:
    external:
      name: backend